src/components/admin/index.jsx
src/components/assistant/index.jsx
src/components/books/index.jsx
src/components/chat/index.jsx
src/components/collections/index.jsx
src/components/common/index.jsx
src/components/games/index.jsx
src/components/home/index.jsx
src/components/hubs/index.jsx
src/components/input-hub/index.jsx
src/components/kids/index.jsx
src/components/layout/index.jsx
src/components/live-tv/index.jsx
src/components/live-wallpaper/index.jsx
src/components/manga/index.jsx
src/components/media/index.jsx
src/components/onboarding/index.jsx
src/components/performers/index.jsx
src/components/player/index.jsx
src/components/search/index.jsx
src/components/settings/index.jsx
src/components/sports/index.jsx
src/components/system/index.jsx
src/components/tools/index.jsx
src/components/ui/index.jsx
src/components/vault/index.jsx
